import { CourseLoopScraper } from '../scrapers/strategies/courseloop';
import { chromium } from 'playwright';

async function debugUtsScraper() {
  console.log('🐞 Debugging UTS Scraper...');

  // Mock Config matching seed.ts
  const utsConfig = {
    baseUrl: 'https://coursehandbook.uts.edu.au',
    routes: {
      base: 'https://coursehandbook.uts.edu.au',
      subject: '/subject/current/:code',
      discovery: '/sitemap.xml'
    }
  };

  const scraper = new CourseLoopScraper('UTS', utsConfig);
  const browser = await chromium.launch({ headless: true });

  // Test Case 1: Known valid code from uts_codes.txt (31251)
  const validCode = '31251'; 
  console.log(`\n🧪 Testing Valid Code: ${validCode}`);
  try {
    const result = await scraper.scrapeSubject(browser, validCode);
    console.log(`Result: ${result.success ? '✅ Success' : '❌ Failed'}`);
    if (!result.success) {
        console.log(`Error: ${result.error}`);
    } else {
        console.log(`Found: ${result.data?.name}`);
    }
  } catch (e) {
      console.error('Exception:', e);
  }

  // Test Case 2: Known valid code from uts_codes.txt (41033)
  const validCode2 = '41033';
  console.log(`\n🧪 Testing Valid Code 2: ${validCode2}`);
  try {
    const result = await scraper.scrapeSubject(browser, validCode2);
    console.log(`Result: ${result.success ? '✅ Success' : '❌ Failed'}`);
    if (!result.success) {
        console.log(`Error: ${result.error}`);
    } else {
        console.log(`Found: ${result.data?.name}`);
    }
  } catch (e) {
      console.error('Exception:', e);
  }

  // Test Case 3: Hypothetical Invalid Code (generated by range)
  const invalidCode = '31000'; // Just outside range? 
  console.log(`\n🧪 Testing Likely Invalid Code: ${invalidCode}`);
  try {
    const result = await scraper.scrapeSubject(browser, invalidCode);
    console.log(`Result: ${result.success ? '✅ Success' : '❌ Failed (Expected)'}`);
    if (!result.success) {
        console.log(`Error: ${result.error}`);
    }
  } catch (e) {
      console.error('Exception:', e);
  }

  await browser.close();
}

debugUtsScraper().catch(console.error);
